### ISSUE TITLE
Newer jenkins to avoid crumbs/CSRF issue and newer Java.

### ISSUE THREAD

**Issue by vpomuran** [Juniper/nita-jenkins#22]
Hello ,
 A java EOF warning in Jenkins:
 
Java 11 end of life in Jenkins
        You are running Jenkins on Java 11, support for which will end on or after Sep 30, 2024. Refer to [the documentation](https://jenkins.io/redirect/java-support/) for more details.

To sum it up it makes sense to upgrade Java version and Jenkins version to the latest stable.

PS. The subject os somewhat misleading, I just cannot change it, sorry. Jenkins version is pretty fresh so it is about java.

**Comment by ian-jarrett** [comment]
Closed, because it is a duplicate of issue #15

**Comment by ian-jarrett** [comment]
Closed, because it is a duplicate of issue https://github.com/Juniper/nita-jenkins/issues/15
