### ISSUE TITLE
cli_scripts look for docker-compose.yaml

### ISSUE THREAD

**Issue by ian-jarrett** [Juniper/nita-jenkins#5]
The following cli_scripts look for "docker-compose.yaml" whereas the file is actually called "docker-compose.yml" (without the "a"):
- nita-cmd_jenkins_down
- nita-cmd_jenkins_restart
- nita-cmd_jenkins_start
- nita-cmd_jenkins_status
- nita-cmd_jenkins_stop
- nita-cmd_jenkins_up

**Comment by aburston** [comment]
Fixed while making scripts work with docker-compose installation. Oops, sorry @ian-jarrett
