### ISSUE TITLE
Update known issues (jre lib version)

### ISSUE THREAD

**Issue by hribeiro-jnpr** [Juniper/nita-jenkins#9]
Update documentation regarding new known issues and workarounds for the current build. Specifically for the jre lib version mismatch in newer Ubuntu instalations

**Comment by wildsubnet** [comment]
This is updated under [known issues ](https://github.com/Juniper/nita-webapp#known-bugs-and-irritations)

**Comment by hribeiro-jnpr** [comment]
Great! I'll close the issue! thanks!
